# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Find Gradle project directory
      id: find-directory
      run: |
        # Search for the directory containing build.gradle or settings.gradle
        PROJECT_DIR=$(find . -name "build.gradle" -exec dirname {} \; | head -n 1 || find . -name "settings.gradle" -exec dirname {} \; | head -n 1)
        echo "Found project directory: $PROJECT_DIR"
        echo "::set-output name=project-directory::$PROJECT_DIR"
      shell: bash
    - name: Build with Gradle
      uses: gradle/gradle-build-action@latest
      with:
        arguments: build
        build-root-directory: ${{ steps.find-directory.outputs.project-directory }}

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@latest
      with:
          arguments: build jacocoTestReport
          build-root-directory: tests

    - name: Upload JaCoCo coverage report as a workflow artifact
      uses: actions/upload-artifact@v3.1.1
      with:
          name: jacoco-report
          path: tests/build/reports/jacoco/test/html/
          
    - name: Upload library JAR
      uses: actions/upload-artifact@v3.1.1
      with:
          name: lib.jar
          path: core/build/libs/core-1.0.jar
    

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
